### ISSUE TITLE
about/ and tags/ look broken

### ISSUE THREAD

**Issue by Yoric** [nodejh/hugo-theme-cactus-plus#1]
Looking at http://themes.gohugo.io/theme/hugo-theme-cactus-plus/ (and my attempt to use hugo-theme-cactus-plus), neither `Tags` nor `About` seem to work.

It's a shame, because I like your theme :)

**Comment by Yoric** [comment]
Probably related to https://github.com/digitalcraftsman/hugo-cactus-theme/issues/20 .

**Comment by nodejh** [comment]
@Yoric Thank you very much! I have merged your pull request 😉
