### ISSUE TITLE
still problems with tags

### ISSUE THREAD

**Issue by tcbtcb** [nodejh/hugo-theme-cactus-plus#10]
hello - I saw the previous (closed) issue with the 'about' page, and make the file change to /layouts/section/about.html worked great. Thanks.

I still cannot get the Tags page to render. Are there any possible suggestions for that?

**Comment by nodejh** [comment]
@tcbtcb Thank you very much, I will have a look and fix it soon.

**Comment by filosofikode** [comment]
@tcbtcb 

- First: move (and rename) `themes/cactus-plus/layouts/tags/single.html` to `themes/cactus-plus/layouts/taxonomy/tag.terms.html`
- Second: Rename your `content/tags/index.md` to `content/tags/_index.md`

Thanks.

**Comment by nodejh** [comment]
@tcbtcb  @filosofikode

I have fix this problem. I am truly grateful for your help！
