### ISSUE TITLE
.Now will be deprecated with Hugo v0.20

### ISSUE THREAD

**Issue by digitalcraftsman** [nodejh/hugo-theme-cactus-plus#11]
`.Now` will be deprecated replaced with the `now` template function in Hugo v0.20 which eventually will be released on Monday. It's likely that the deprecation will cause builds to fail.

**Comment by nodejh** [comment]
Thanks for your advice, I have changed `.Now` to `now` template function [https://github.com/nodejh/hugo-theme-cactus-plus/commit/ff2a1e2433aa299ae12715e4ff3e7cc341f08061](https://github.com/nodejh/hugo-theme-cactus-plus/commit/ff2a1e2433aa299ae12715e4ff3e7cc341f08061).

**Comment by digitalcraftsman** [comment]
Great @nodejh. Btw, Hugo v0.20 will be released on Monday.
