### ISSUE TITLE
From Hugo 0.24 this must be provided in the archetype file itself

### ISSUE THREAD

**Issue by Taubin** [nodejh/hugo-theme-cactus-plus#13]
`$ hugo new post/blah.md
WARNING: date and/or title missing from archetype file "/home/user/site/themes/hugo-theme-
cactus-plus/archetypes/default.md".
From Hugo 0.24 this must be provided in the archetype file itself, if needed. Example:
+++
title = "{{ replace .TranslationBaseName "-" " " | title }}"
date = {{ .Date }}
draft = true
+++`

**Comment by nodejh** [comment]
Thank you very much，I have fixed this: https://github.com/nodejh/hugo-theme-cactus-plus/commit/960e71e89942006dd005eec737da868bfed7ce18
