### ISSUE TITLE
Template Customization

### ISSUE THREAD

**Issue by mrwullah** [nodejh/hugo-theme-cactus-plus#24]
Hi @nodejh ,

Thanks a ton for creating this beautiful template. I'm simply in love.

I need to customize the template.

1. How do I display post excerpts of posts on home page?
2. What's the cost for tags page?
3. How to add "about" under a post?

You may find more appropriate to update the theme 'docs' file with such general thingies.

Thank you!

**Comment by nodejh** [comment]
I have updated some features such as excerpt and tags page , you can use latest version.

#### 1. How do I display post excerpts of posts on home page?

You can use `<!--more-->` summary divider split article, content that comes before the summary divider will be used as that content’s summary.

Also you can describe your summary in post's front matter use `description` property, and set `useDescriptionReplaceSummary = true`,  e.g.

```sh
title = "The post title"
description = "This will be used as post's excerpt if you set useDescriptionReplaceSummary = true"
tags = [
    "go",
    "golang",
    "templates",
    "themes",
    "development",
]
date = "2014-04-02"
categories = [
    "Development",
    "golang",
]
```

#### 2. What's the cost for tags page?

You only need add tags in psot's front matter, the theme will automatic render the tags pageat `http://your_domain_name/tags`.(e.g. [http://nodejh.com/tags/](http://nodejh.com/tags/))

#### 3. How to add "about" under a post?

The theme support an about page. If you want to add "about" under a post, you may edit the file [layouts/_default/single.html#L37](https://github.com/nodejh/hugo-theme-cactus-plus/blob/master/layouts/_default/single.html#L37) and add your "about",  this will render at each post page. e.g.


```html
 <section id="post-body">
       {{ .Content }}
 </section>
</article>

// add "about" here and this will render at each post page
```

**Comment by mrwullah** [comment]
Thank you! :)
