### ISSUE TITLE
Tag-cloud Taxonomy Base URL Issue

### ISSUE THREAD

**Issue by jenic** [nodejh/hugo-theme-cactus-plus#28]
The /layouts/taxonomy/tag.terms.html file uses `/tags/` prefix which breaks (HTTP 404) the tag-cloud links when using a baseURL such as "https://www.example.com/blog/" where tag links are then pointing to "https://www.example.com/tags/tag"

Removing the "/tags/" portion in my own layouts/taxonomy/tag.terms.html resolved the issue:
```
11c11
<                     <a href="/tags/{{ $name | urlize }}" rel="{{ len $taxonomy }}">{{ $name }}({{ len $taxonomy }})</a>
---
>                     <a href="{{ $name | urlize }}" rel="{{ len $taxonomy }}">{{ $name }}({{ len $taxonomy }})</a>
```

However now this is a relative link, not sure that is how you want to handle this. Thought I'd let you know though!

**Comment by nodejh** [comment]
I wrote the wrong code. I have changed the relative link https://github.com/nodejh/hugo-theme-cactus-plus/blob/5626b004a4b249caebde9de1b45db4b9748c76fa/layouts/_default/terms.html#L14

You can use the latest version of this theme.

**Comment by jenic** [comment]
Great thanks!
