### ISSUE TITLE
Any idea why Disqus don't show up?

### ISSUE THREAD

**Issue by vdubedout** [nodejh/hugo-theme-cactus-plus#29]
Hi, I'm trying to setup my website with this theme. I'm coming from #Ghost and I can't find how to activate disqus here. I migrate all this yesterday and I probably miss something. Any help is welcome. Thanks :)

[An Article as Example](https://dubedout.eu/2016/11/13/viewpager-indicator-libraries-you-should-know/)

my config.
```
# Site settings
baseurl = "/"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "en"
title = "Experiments"
theme = "hugo-theme-cactus-plus"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-73551613-1"
hasCJKLanguage = false

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[params]
	name = "Experiments"
	description = "Experiments around Coding, Android, Architecture, and what goes through my mind"
	bio = "Human vs Android"

  # Enter optionally your twitter account
  # twitter = "your_twitter"
  enableRSS = true

  # Disqus comment
  disqusShortname = "vi-blog"
  # Disable disqus comments by set `enableDisqus = "false"`
  enableDisqus = true

  # Duoshuo comment
  # duoshuoShortname = "your_duoshuo_short_name"
  # Disable duoshuo comments by set `enableDuoshuo = "false"`
  enableDuoshuo = false

  enableGithubIssuesTips = false

  # Enable googleAnalytics
  enableGoogleAnalytics = true
```

**Comment by nodejh** [comment]
@vdubedout Uh, thanks for your feedback. There is some thing wrong with the theme, I have fixed it https://github.com/nodejh/hugo-theme-cactus-plus/commit/22aa435ab356e989e4637fa3fa8071d25ade5823. You can update the theme (ex, `cd themes/hugo-theme-cactus-plus && git pull` ) and then you will see disqus show up.

**Comment by vdubedout** [comment]
Ow awesome, any way for me to pay you a beer? vincent@dubedout.eu

**Comment by nodejh** [comment]
Thank you for for the glowing praise. You’re too kind 😊. This is my PayPal https://www.paypal.me/nodejh
