### ISSUE TITLE
How to Display 'toc' On The Top of Articles?

### ISSUE THREAD

**Issue by mrwullah** [nodejh/hugo-theme-cactus-plus#32]
Hi, I have seen you are using Table of Contents, how we can use it?
Reference URL: http://nodejh.com/posts/wechat-scan-qr-code-to-login/#3-%E6%94%B9%E8%BF%9B

**Comment by nodejh** [comment]
Set `enableToc = true` in `config.toml` and the theme will automatic render table of contents.

  https://github.com/nodejh/hugo-theme-cactus-plus/blob/98cd7f9f63a9667b0c70cff8b9525667b555a871/exampleSite/config.toml#L19 

The value is `true` default, maybe you could use the latest version of this theme?

**Comment by mrwullah** [comment]
Awesome, thanks!
