### ISSUE TITLE
Template does no longer render /posts path

### ISSUE THREAD

**Issue by flypenguin** [nodejh/hugo-theme-cactus-plus#34]
commit ID 5c83c15

The file `/layouts/partials/nav.html` contains this snippet:

```
<a href='{{ .Site.BaseURL }}posts'>{{ with .Site.Params.archive }}{{ . }}{{ else }}Archive{{ end }}</a>
```

It seems the `/posts` path is no longer rendered by the template though. When I click the link I get a 404 error.

`/post` works though, but I can't override it in the config due to its static nature ;)

**Comment by nodejh** [comment]
The hugo docs (https://gohugo.io/content-management/organization/) specify that the default location for a user's posts is in the `posts/` directory, so I have change it. PR ac0a0d168661f8453a9ec8436a3581c96b59cf44

And the `posts` is base on  organization of content source. 
Maby you could update your content directory
  
For example
```
└── content
    └── about
    |   └── _index.md  // <- https://example.com/about/
    ├── posts  // Maybe your directory name is `post`
    |   ├── firstpost.md   // <- https://example.com/posts/firstpost/
```
