### ISSUE TITLE
Override partials in templates

### ISSUE THREAD

**Issue by nielsen** [nodejh/hugo-theme-cactus-plus#35]
Hi there!

Great theme 👍 -- Is there a programmatic way (config, file structure) to override partials that are being included in the theme-layouts/ folder without having to copy up the whole file and the partials (with a couple edits) into the base folder?

Thanks

**Comment by nodejh** [comment]
Hello, @nielsen 

I'm sorry that I have no idea about that. I think you could rewrite the  partials. 🤔
