### ISSUE TITLE
Missing Archive section

### ISSUE THREAD

**Issue by b1azk0** [nodejh/hugo-theme-cactus-plus#41]
Forgive me so many questions but I really like your template and prefer to spend more time configuring it than start looking for alternatives.
Your site http://nodejh.com/post/ has a nice archive section that is missing after setting up an empty site (with Rstudio blogdown).
Im not sure which parts of code I should modify to make it look like yours. Any hint would be very appreciated. 
If that is of any help my source is here:  https://github.com/b1azk0/blog

**Comment by b1azk0** [comment]
I solved this by moving all my post rmd/html files from 
`/post` directory to `/posts`

**Comment by nodejh** [comment]
Hi @b1azk0, it's  because of the theme use `posts` as articles directory (see: https://github.com/nodejh/hugo-theme-cactus-plus/pull/30), Rstudio generates `post`  directory.
