### ISSUE TITLE
Personal avatar does not always replace default avatar although deleted

### ISSUE THREAD

**Issue by lorenzwalthert** [nodejh/hugo-theme-cactus-plus#57]
Thanks for this wonderful theme, I really like it. However, I changed all avatar images but when I check the website on my phone, I still see the default avatar. During loading though, the right avatar is displayed. The problem only occurs on my mobile device, not on my desktop. But it occurs on some other desktop computer too. Any ideas what the problem could be? I am not using plain Hugo, but [blogdown](https://bookdown.org/yihui/blogdown/), which extends Hugo to work with Rmarkdown files, among other things.

* Here is the built webpage: http://5b1fcf013672df1d7c2e7a55.lorenzwalthert.netlify.com
* This is the source code: https://github.com/lorenzwalthert/blogdown-cactus/pull/1

Any help appreciated.

**Comment by nodejh** [comment]
When I open the built webpage http://5b1fcf013672df1d7c2e7a55.lorenzwalthert.netlify.com on my mobile, the avatar is right. 
![image](https://user-images.githubusercontent.com/10287125/41296232-1592a8cc-6e8f-11e8-9556-ac3e725b6e30.png)


Probably because of caching?

**Comment by lorenzwalthert** [comment]
Thanks, you might be right. I will continue to observe it.

**Comment by lorenzwalthert** [comment]
Ok. I think we can close this. Thanks
