### ISSUE TITLE
Trying to add more pages

### ISSUE THREAD

**Issue by colorchestra** [nodejh/hugo-theme-cactus-plus#66]
Hi!

Is it possible to add custom pages to my Hugo blog using this theme? Just like the "Projects" page on http://nodejh.com/. Is that easily possible or is it more of a hack? 

I've tried copying the `content/about` directory to `content/projects` and adding `projects = ""` to the navigation links in config.toml, but that didn't help.

Thank you!

**Comment by nodejh** [comment]
Hi, 

Also need adding projects' link to `/layouts/partials/nav.html`, like this:

https://github.com/nodejh/hugo-theme-cactus-plus/blob/bbf185efc04dbbbb65c82d1d099c03891464a265/layouts/partials/nav.html#L8

**Comment by colorchestra** [comment]
That worked, thank you!
