### ISSUE TITLE
Is there a way of making the content layout wider?

### ISSUE THREAD

**Issue by xzenggit** [nodejh/hugo-theme-cactus-plus#80]
Hello, 
Thanks for opening-source this theme. It is really nice!
I'm trying to make the content layout wider. I feel like the white spaces on both sides are too wide. Is there a way of reducing the white space? Thank you!

**Comment by shivamdixit** [comment]
I added the following CSS to a CSS file in `static` directory:

```
/* Increase the width of the content */
#wrapper {
    max-width: 750px;
}

#wrapper.home {
    max-width: 750px;
}

.profile #wrapper {
    max-width: 750px;
}

#wrapper.post {
    max-width: 700px;
}
```

Adjust the max-width to the value that you want. PS: don't forget to include the custom stylesheet in `config.toml`.

**Comment by xzenggit** [comment]
> /* Increase the width of the content */
> #wrapper {
>     max-width: 750px;
> }
> 
> #wrapper.home {
>     max-width: 750px;
> }
> 
> .profile #wrapper {
>     max-width: 750px;
> }
> 
> #wrapper.post {
>     max-width: 700px;
> }

Thank you @shivamdixit . It works! Really appreciate it!
